$ANSIBLE_VAULT;1.1;AES256
38353162303965306637343766633861643534313337613730386433343137386337636430653666
6633333866653463616166663638656535646532356634340a373564646263323066316532333061
36373939376664383434353461376237343535653730326437356636653837633433623935306632
3465643139623735390a663131663363636663313331346664376636623736633465383662366439
63643236663862383133303563343230356661366336366530303464393463306662326361326432
61363138386365383164653635653763373830383665613439623336393362373764333963386665
66643032653137323765316338383264343032613764363132633035306630653038383466363531
36623339346536323232306364313735656337343931363934336264346465303333323631653463
35616134636239333638316637363265653432323862663131373734383065646631383535636166
3239383263313030376463343061613635633366383664396564
