$ANSIBLE_VAULT;1.1;AES256
38316334316166303564656165316462313337353032613434333263333434383062373262336534
6263626139613666323934376335393265333963643831340a393466323735336631636564353937
64666137313266353466633036333939336465356136333130663663356331613733333265393039
3436656535303962350a663161646665383435336134343731373733613462313531323832616531
32656463303934666537396166393130636537313430373433396335616631656635326562346133
64643363356639646435383063656365353531396437386666376536333831343263613561356337
32383461613838326434393165323061303766666435653565356131656139366635313638626465
37353336643937663331303262376532373231356361646238346633306465343236633331323134
35633862336166323339306461383436353362656461363939343263366333376539383133663731
62356238613463373131393335326136306361626463643435643161386132306430663430616666
66343665343130343838373065396330323664353438343263613761356463363236356566336236
63363031393234663161626131393039636134346361323739643737303733386335616661333933
36373731306664356366393163326237633062386235663161343735346133303737373834303933
35663832303436386266363536643533616163343036316265313366326435623163623237633338
34373965356132626364366561656561663138363932303966663338663532306164373164653835
61333838656232363061
