$ANSIBLE_VAULT;1.1;AES256
31626430616436306239356239633866386432376434383437663538623762316364303461643933
3161623435393135323737666461633161363539333430660a366230366662616461386465616632
66623661663565323133643163663432623931646237656130393563303734343337316335326437
3166393238633664630a323332346135656134373162623562663365313332656333643437626266
38643963663461336335663963623139393662396663386438613166376134346465353530393732
64633237383036333035616465316139363962663231643062343938373835373337623536623266
32336233623333633261343337633061383931323164346134323536393435383561623061343163
35386662353139383833383038303632626336666339653336373561613436326164363165663264
38386239353764303930613766663732633733646463326266373639316139393337353131376530
6462613938333864356133323261346635373936323766626462
