$ANSIBLE_VAULT;1.1;AES256
37396639306634626261623430326532353062633539633361393266613762333638303633313731
6339353063313934626264663762613230653834663062370a366261343862653834316237383434
36626437376133306235383737633232363066383335373334626238643131623137366662616666
6330643866303239340a346533353736653166353935333033653865623261363062303132616265
32313134663431626338323337323464303333653462356137346635653636393663623134383965
36326363623961656362346566366566633533326463663133623733623665663036383865623366
61343730633131616333333139323634313562376262613037343362663361383239323566616466
34613961613332386133346339636438383466343633623966323663613161623465613465383361
30366335343665393234386564393236643034623566393564353737383462303165636438623935
3036343233363065646162313131333338396333383837653835
