$ANSIBLE_VAULT;1.1;AES256
61346631303531353863336532353337623539363662306137336464656661643733643535636462
3130303363333138313361616630363566303639323231620a323566623961653562343538386366
63363965373965633266343430383764346634343665303532613333313866666333303939393635
3139663265643862380a666636626233303037633635383432663336303031323661636266316431
32326362386531663932623038663965653562663238323936353963363465333566386432313366
37333165386137346433663962323466333563343762613437663134303136303630303935363930
62343361666239666639366164653032316531376334653462623633383433306337666338393964
34333831376337313236643261643066303664646363646431356463633435323836643536613133
36613034626430323634623965336134303361323632656334626361353038616638346164376630
62643434666235623638636338636165333530643738306430666138386632636336353064386336
62363961313431313865393439633564306532663166643861636136386562653536653362393662
64336365636662386466633433633034313736343264393539313562343335313463613064346162
34636339656333313133363435623035643631316537393739653431623064353133373636626363
64616139316634356461653238383032333333653461313631373461373363313939383030613036
39653261383331346162313761636637373037626439666232646462323535623633656130383238
64663033393535643332
