$ANSIBLE_VAULT;1.1;AES256
36633662643230366437396561303535356566303138376365383465396365356561666532373835
3166356334366136393563326132633037383765643164350a636161653965326436633233363761
31663465363235663363633034353364366462613161626431363737646464633732353836376264
6664363731363266610a333832313366363430336661363731623031356566373034396235613939
64333635666366346137633638633266646538626135333331393565663363373465343964323033
65333231646366663235613033653165326565373738393632636166613732386432383138346663
34393538306461613864616230343561653738313064656463336236393333313732383939333462
64373066316238383662366530326164343166303235386533323762376438326134613263303738
33373362303639343531343738656662626536306266613666313737366435313734663130313761
63613039633364336565613561323338616562356566326130316433306461623964383839346364
62636335393636393166386164323763616437383035383065316439333033643734386362396339
66303030643934623865663334323738396665363830623466666337653932343130326633346363
65313164333164303532623130396363656233616637373161326534386662613835636465646532
66313038373630663961383532666365336565613339383030383536346438336538313363313333
64633965363633343439386261363663333664363962373038376161363834323335336635303434
62656139326635336631
