$ANSIBLE_VAULT;1.1;AES256
37306339383261613061333431633464316139313065633831356464383465386431653039313538
3962306430666232313232376533313962376435386134640a323865616437316134316465663861
31323931336663646637363936643361356132633136653139643532323535373466343335666638
3130383265333632340a376333303433663462353862663432623239353434346331326638336639
32666539303132653733326138326165396633303736343661313162633531663935643365613762
31333238363632346339333730376665323561663834316262323337346235663966386235386461
31363439306339383633306438383338376265396235306230363761313633656333316432613964
36623330643037353231626165383832343333313039653464383233356431643638336361386463
39373561303862306432306233396332646634363135363837643761363734633165383563636162
3664353636323131646439313433333531393133386161366565
