$ANSIBLE_VAULT;1.1;AES256
37303563653839386533653034313533353061643366376636646135623962363830656361633462
6663356463366365303565653539396533666331323962360a346134303163326532393138316263
38333630316435623363363131663130623037353139303365366534376166373165373861333265
6463343430306631630a343535623938323536616663666130393162633737383665663562343964
39326139663266376238626432333863643466313230353766303531613835313736376562333132
66643764363866623332303363383566623262633063373034303866666563666433363931376231
38316238353436643734336461633038303165383931393536633433643234313364616632346537
61383936383934313263663335623539343966313866653232313266303837356630326138343037
34393233643535323637646662646531363864313836616363633639626230393636373730383730
6565343838613766303632616464393264383932326436663635
