$ANSIBLE_VAULT;1.1;AES256
32373563653366313766323832666331623634346161343138613432316234666363323632666431
6432363961613433653637643137376661646434383332370a353666326632303130613437356464
30356432623365323766376435663562623761346637636433633535336130663663323633633466
3964363631366161640a376564363739326435323734663333356436346434653839373061313061
64363564306133643930363830656137616338356263346432393466346666356436303863366264
31633732303238333165333461396564633733643965356339346466346539646439323335313963
33646464373434356363313939336130323835663932383038613231663034386564386138346637
30633937663961633837646435333965656163343666313635323637616339386433326661366461
62343438356663393636663635633262663365323231343562316530393564663032663638333761
63653639323633623138323166653335323732633866353462333366383230643232616238336533
62653337656639666332373734366231623637616637656231313835323565306539623630626534
39306137636664626562303761633337313932306337636538663166333463323336336634366662
61626330323938623561343438643265623264376663393762643362323839353364656637316636
30376432643232303735343530353437373031613262643637653833316133366461396563376139
62383463393735383166633863393438383763656632333638663762366266353463646531613135
64376232303133303539
