$ANSIBLE_VAULT;1.1;AES256
64613834393665666666643537613130353361383037643031613963343963353563333762353666
3636663137393533623939633730343735353733373736390a623132333930333237393866663930
35383362653338396431396464326166363436653266656362336638646437323966323138646163
3235643632373364340a633233663761316666306564393131653935343762373234303365646562
64616365333965666134653638613162303232373931346231633235633439393837623636333732
30643631623538313364313739383965326262666230326166343463316130643231623636643466
35333231643765393636323562313133303162353364623062313839303139386339303336313830
36303666656262336239633939323935393531306635363134646264336562303037353034353563
61613961326162316362333463316431626232376433323433363832636636343562346235343830
61646362383863333637333063663938626530306363633666333435656535626133646363303365
62616264346330663930623532623332333633316637646433303232616439306463323437383762
65643537386461616439313338316539346535336564666437333832356631353534306466313366
34643239393366663339633739623461643461666461666633363838316631343766313433333731
3864613636636631396565396466346630323934653234343534
