$ANSIBLE_VAULT;1.1;AES256
34363866333831393838376637643063306337646264343638363463653138393434653734313836
3538383632326461323464636165343339363061346438650a306234313231323266613331623934
30383662363530386138363239366136623930653437376362653636386138653466646338396332
6237663236653238350a633066663736396261373334636163356436643135643732383530343963
65633239383130393564346163366661656465343166303936653136383334616331386461373936
39386431383437316264656561623236336662366438396136656539653862613561653731663566
31373537373431303637323966393166373336346562333135633733356430613139326231356335
30653033393236366638313563366133343733383662336465326463393431656461663839376538
36623832353334303734373438396663393465373534626561663864613630346535336139623161
6362616561666336363166656330303433643162343834363735
