$ANSIBLE_VAULT;1.1;AES256
30646339326233653536626265653764343939303437613334393763323861353463393466613231
3933373064623632663338663763376634616361336537320a343265346337346632316364616331
34613137646235396361333062383733366262366334643131616163333730396564646465623337
6433363036643761350a646539343264313837366438393465613235353036376366346364356234
62656666626234616634366535326438383666323733633234363735323437353865363263386135
30663639373434626236333039636436366362633463333365643133336433373863636139333064
32626334623866363764393036363037376239336365613563653931656237663632626134313462
37316666333865383034323130663561663031653337336330306135623064376631363762653535
63373634353139346663333937333266316466353166643861396366326633643666353936656165
61363238323836336530333364336138343937343232373137353737333363313938396639383735
62383863313562363963363834633639383332336635613966336532393838663032373861303530
63646137333739393630393936346463313535623364326339393462616339626165306130306361
65366464313438623431346336343935663831386130326461616232366132343866643133373438
3132356462623930333234366535663064323639653539653137
