$ANSIBLE_VAULT;1.1;AES256
32323238613634373233653233623334633331313736383839656133346264616335383334386635
6266396334373935373937353633666236303132343961300a336439646338336538306161656462
32383766666365656265313433326666313162643664316466313462303961353466653737663464
3234366237343161610a306336623531633638373434643466386161633936336338373034303965
32323861656138356335636633313532306561303536616464646134396130616166323538393061
30383930346235646436636463306630613439346635333432633230363766623566623662343164
35363766643237656263346333633365643164303136306562633365373865663765303239643461
33356131353766376231326434636430376366613831613036303134633932313863333834326264
37383433326332643430633862306638643635633333393435363661326339633330396335663036
3430353534323464306231356432646538616635633233373432
