$ANSIBLE_VAULT;1.1;AES256
39396364656430373265393433386263666631356462333165363430623235346337393130353564
3037616533616561323339393531333762663137363833360a333538396633386364366561343364
66376137633230646132343835623661356537643635336365363131626661316339383937663932
6330393964666333660a343132346434653164393139326534656230306464336465613662373133
33623730633637623236353863613734616333316233306361323064363734623736626163356264
38363664613434373762383564343064666431366161613962353264636331623633346162353934
63373136363038313566333732636162313261623231363631373035353435626138306137306238
31326138366265333431306631306566363864616435633034336265663430303131303533616463
34323535303264343033633433636639393830613134353235663034373337393564393862626330
3537356234636562306131376638306230396330633030373663
