$ANSIBLE_VAULT;1.1;AES256
64623466623066643038383034623665656265313533316562633034643131376364316235373536
3634626262326130306638343130313535623833363837620a653931333439613462333634326235
35376166313566633636663232613336653764616464643730333231653163636262393436613333
3737316464313032630a323365623861323732386639363838633766346661353334366633636533
34373631643230373065313435623732383933656538303931313164363730393664323936373439
66386433356261316132343163353766343561373664626665383330643538616439343363613632
66363766363539356439663232626532663231613537333033346562376264333838333631353561
63316133626238626466646435313636343837666536373164613636633063636239626265373830
35646537356162306661343662356538343830643431343162323263653430663136653366646231
39303036633435653039373638303234383764633362373033316466326238326566633635663230
36323661393632336464613436656661333966656365646238386532356339366230343362616531
36306265386365393363613361363266373461616637316263613735386534653333383237386238
35643631623661643830633331303839353831356263326138616566313864383330383266356335
3032306531303132346161366331616463636265383036306235
